name: WakaTime Readme

on:
  workflow_dispatch:
  schedule:
    # Se ejecuta cada día a las 00:00 UTC
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Actualizar WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@latest
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # Configuración para que se muestre en el README
          COMMIT_BY_ME: "True"
