name: WakaTime Readme

on:
  workflow_dispatch:
  schedule:
    # Se ejecuta cada d√≠a a las 00:00 UTC
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Actualizar WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@v1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          # Configuraci√≥n para que se muestre en el README
          COMMIT_BY_ME: "True"
          COMMIT_MESSAGE: "ü§ñ Actualizar estad√≠sticas de codificaci√≥n de WakaTime"
          # Puedes a√±adir m√°s opciones como SHOW_LANGUAGE_PER_REPO, etc.
